// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckcmazjxffqnmoownvap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrY21hemp4ZmZxbm1vb3dudmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNTU3MTksImV4cCI6MjA3MDYzMTcxOX0.hs11avqdw6UxHF5izAn2trMShgKpPdgSHOzUIPUW0rM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});